/***
 *
 * List of Car Model
 *
 ***/
export const ModelCodes : {[key: string]: string} =
{
  "ALF-brera":"BRER",
  "ALF-giulietta":"GIUT",
  "ALF-giulia":"GIUL",
  "ALF-giulia gta":"GIUG",
  "ALF-gt":"GT",
  "ALF-mito":"MITO",
  "ALF-stelvio":"STEL",
  "ALF-spider":"SPID",
  "ALF-147":"147",
  "ALF-156":"156",
  "ALF-167":"167",
  "AUD-a1":"A1",
  "AUD-a2":"A2",
  "AUD-a3":"A3",
  "AUD-a4":"A4",
  "AUD-a5":"A5",
  "AUD-a6":"A6",
  "AUD-a8":"A8",
  "AUD-q2":"Q2",
  "AUD-q3":"Q3",
  "AUD-q5":"Q5",
  "AUD-q7":"Q7",
  "AUD-rs3":"RS3",
  "AUD-rs6":"RS6",
  "AUD-s1":"S1",
  "AUD-s3":"S3",
  "AUD-tt":"TT",
  "BMW-serie 1":"S1",
  "BMW-serie 2":"S2",
  "BMW-serie 3":"S3",
  "BMW-serie 5":"S5",
  "BMW-serie 6":"S6",
  "BMW-serie 7":"S7",
  "BMW-x1":"X1",
  "BMW-x3":"X3",
  "BMW-x5":"X5",
  "BMW-x6":"X6",
  "BMW-z3":"Z3",
  "BMW-z4":"Z4",
  "CHE-captiva":"CAP",
  "CHE-cruze":"CRU",
  "CHE-aveo":"AVE",
  "CHE-orlando":"ORL",
  "CHE-spark":"SPA",
  "CHE-trax":"TRA",
  "CHE-camaro":"CAM",
  "CHR-300c":"300C",
  "CHR-commander":"COM",
  "CHR-grand cherokee":"GCH",
  "CHR-grand voyager":"GVO",
  "CHR-pt cruiser":"PTC",
  "CHR-saloon":"SAL",
  "CHR-sebring":"SEB",
  "CHR-sedan":"SED",
  "CHR-voyager":"VOY",
  "CIT-berlingo":"BER",
  "CIT-c-crosser":"CCR",
  "CIT-c-elysée":"CEL",
  "CIT-c1":"C1",
  "CIT-c2":"C2",
  "CIT-c3":"C3",
  "CIT-c3 aircross":"C3AC",
  "CIT-c3 picasso":"C3PI",
  "CIT-c3 pluriel":"C3PL",
  "CIT-c4":"C4",
  "CIT-c4 aircross":"C4AC",
  "CIT-c4 cactus":"C4CA",
  "CIT-c4 grand picasso":"C4GP",
  "CIT-c4 picasso":"C4PI",
  "CIT-c4 spacetourer":"C4SP",
  "CIT-c5":"C5",
  "CIT-c5 air cross":"C5AC",
  "CIT-c6":"C6",
  "CIT-c8":"C8",
  "CIT-dispatch":"DIS",
  "CIT-ds3":"DS3",
  "CIT-jumper":"JPR",
  "CIT-jumpy":"JPY",
  "CIT-nemo":"NEM",
  "CIT-relay":"REL",
  "CIT-saxo":"SAX",
  "CIT-space tourer":"SPT",
  "CIT-xsara":"XSA",
  "CIT-xsara picasso":"XSAPI",
  "DAC-dokker":"DOK",
  "DAC-duster":"DUS",
  "DAC-lodgy":"LOD",
  "DAC-logan":"LOG",
  "DAC-sandero":"SAN",
  "DOD-avenger":"AVG",
  "DOD-challenger":"CHL",
  "DOD-charger":"CHR",
  "DOD-grand caravan":"GRC",
  "DSA-ds3":"DS3",
  "DSA-ds4":"DS4",
  "DSA-ds5":"DS5",
  "DSA-ds7 crossback":"DS7CB",
  "DSA-ds9":"DS9",
  "FIA-500":"500",
  "FIA-500l":"500L",
  "FIA-500x":"500X",
  "FIA-bravo":"BRA",
  "FIA-doblo":"DOB",
  "FIA-ducato":"DUC",
  "FIA-fiorino":"FIO",
  "FIA-grande punto":"GPUN",
  "FIA-linea":"LIN",
  "FIA-punto":"PUN",
  "FIA-punto evo":"PUNE",
  "FIA-panda":"PAND",
  "FIA-qubo":"QUB",
  "FIA-scudo":"SCU",
  "FIA-stilo":"STI",
  "FIA-talento":"TAL",
  "FOR-b-max":"BMAX",
  "FOR-c-max":"CMAX",
  "FOR-cougar":"COUG",
  "FOR-ecosport":"ECOS",
  "FOR-edge":"EDGE",
  "FOR-escape":"ESCA",
  "FOR-explorer":"EXPL",
  "FOR-fiesta":"FIES",
  "FOR-flex":"FLEX",
  "FOR-focus":"FOCU",
  "FOR-fusion":"FUSI",
  "FOR-galaxy":"GALA",
  "FOR-grand c-max":"GCMX",
  "FOR-ka":"KA",
  "FOR-kuga":"KUGA",
  "FOR-maverick":"MAVE",
  "FOR-mondeo":"MOND",
  "FOR-ranger":"RANG",
  "FOR-s-max":"SMAX",
  "FOR-taurus":"TAUR",
  "FOR-tourneo":"TOUR",
  "FOR-transit":"TRS",
  "FOR-transit connect":"TRSC",
  "FOR-transit courier":"TRSCOU",
  "FOR-transit custom":"TRSCUS",
  "HON-accord":"ACC",
  "HON-city":"CIT",
  "HON-civic":"CIV",
  "HON-cr-v":"CRV",
  "HON-cr-z":"CRZ",
  "HON-crider":"CRI",
  "HON-fr-v":"FRV",
  "HON-hr-v":"HRV",
  "HON-insight":"INS",
  "HON-jazz":"JAZ",
  "HON-s2000":"S20",
  "HON-stream":"STR",
  "HYU-accent":"ACC",
  "HYU-solaris":"SOL",
  "HYU-i10":"I10",
  "HYU-i20":"I20",
  "HYU-i30":"I30",
  "HYU-i40":"I40",
  "HYU-ix35":"IX35",
  "HYU-santa fe":"SAFE",
  "HYU-sonata":"SON",
  "HYU-tucson":"TUC",
  "HYU-veloster":"VEL",
  "IVE-daily":"DAI",
  "JAG-e-pace":"EPA",
  "JAG-f-pace":"FPA",
  "JAG-i-pace":"IPA",
  "JAG-xf":"XF",
  "JAG-xk":"XK",
  "JEE-compass":"COM",
  "JEE-grand cherokee":"GCH",
  "JEE-liberty":"LIB",
  "JEE-renegade":"REN",
  "JEE-trailhawk":"TRA",
  "JEE-wrangler":"WRA",
  "KIA-carens":"CAR",
  "KIA-ceed":"CEE",
  "KIA-niro":"NIR",
  "KIA-optima":"OPT",
  "KIA-picanto":"PIC",
  "KIA-pro-ceed":"PROC",
  "KIA-rio":"RIO",
  "KIA-sedona":"SED",
  "KIA-shuma":"SHU",
  "KIA-sorento":"SOR",
  "KIA-soul":"SOU",
  "KIA-sportage":"SPO",
  "KIA-venga":"VEN",
  "LAN-voyager":"VOY",
  "LAN-ypsilon":"YPS",
  "LRR-defender":"DEF",
  "LRR-discovery":"DIS",
  "LRR-discovery 5":"DIS5",
  "LRR-discovery sport":"DISS",
  "LRR-freelander":"FRE",
  "LRR-range rover":"RRO",
  "LRR-range rover evoque":"RROE",
  "LRR-range rover sport":"RROS",
  "LRR-range rover velar":"RROVE",
  "LRR-range rover vogue":"RROVO",
  "MER-classe a":"CA",
  "MER-classe b":"CB",
  "MER-classe c":"CC",
  "MER-classe cl":"CCL",
  "MER-classe e":"CE",
  "MER-classe g":"CG",
  "MER-classe gl":"CGL",
  "MER-classe m":"CM",
  "MER-classe r":"CR",
  "MER-classe s":"CS",
  "MER-classe sl":"CSL",
  "MER-clk":"CLK",
  "MER-cls":"CLS",
  "MER-slc":"SLC",
  "MER-slk":"SLK",
  "MER-sprinter":"SPR",
  "MER-viano":"VIA",
  "MER-vito":"VIT",
  "MIN-cabrio":"CAB",
  "MIN-clubman":"CLU",
  "MIN-cooper":"COO",
  "MIN-cooper s":"COOS",
  "MIN-countryman":"COUN",
  "MIN-coupe":"COUP",
  "MIN-one":"ONE",
  "MIN-one d":"ONED",
  "MIN-paceman":"PACE",
  "MIT-asx":"ASX",
  "MIT-grandis":"GRA",
  "MIT-l 200":"L200",
  "MIT-lancer":"LAN",
  "MIT-outlander phev":"OUTP",
  "MIT-outlander":"OUT",
  "NIS-350z":"350Z",
  "NIS-almera":"ALM",
  "NIS-almera tino":"ALMT",
  "NIS-cabster":"CABS",
  "NIS-cube":"CUBE",
  "NIS-e-nv200":"ENV200",
  "NIS-interstar":"INTE",
  "NIS-juke":"JUKE",
  "NIS-leaf":"LEAF",
  "NIS-micra":"MICR",
  "NIS-micra k12":"MICRK12",
  "NIS-murano":"MURA",
  "NIS-navara":"NAVA",
  "NIS-note":"NOTE",
  "NIS-note e11":"NOTEE11",
  "NIS-np300":"NP300",
  "NIS-nv200":"NV200",
  "NIS-nv300":"NV300",
  "NIS-nv400":"NV400",
  "NIS-pathfinder":"PATH",
  "NIS-patrol":"PATR",
  "NIS-pixo":"PIXO",
  "NIS-primastar":"PRIMA",
  "NIS-primera":"PRIME",
  "NIS-pulsar":"PULS",
  "NIS-qashqai":"QASH",
  "NIS-qashqai j10":"QASHJ10",
  "NIS-serena":"SERE",
  "NIS-terrano":"TERR",
  "NIS-tiida c11":"TIIDC11",
  "NIS-vanette":"VANE",
  "NIS-x-trail":"XTRA",
  "NIS-x-trail t30":"XTRAT30",
  "OPE-adam":"ADAM",
  "OPE-agila":"AGIL",
  "OPE-astra":"ASTR",
  "OPE-astra j":"ASTRJ",
  "OPE-cascada":"CASC",
  "OPE-combo":"COMB",
  "OPE-corsa":"CORS",
  "OPE-corsa e":"CORSE",
  "OPE-crossland":"CRLD",
  "OPE-crossland x":"CRLX",
  "OPE-frontera":"FRONT",
  "OPE-grandland":"GRLD",
  "OPE-grandland x":"GRLDX",
  "OPE-insignia":"INSI",
  "OPE-karl":"KARL",
  "OPE-meriva":"MERI",
  "OPE-mokka":"MOKK",
  "OPE-movano":"MOVA",
  "OPE-omega":"OMEG",
  "OPE-signum":"SIGN",
  "OPE-tigra":"TIGR",
  "OPE-vectra":"VECT",
  "OPE-vivaro":"VIVA",
  "OPE-zafira":"ZAFI",
  "OPE-zafira c":"ZAFIC",
  "PEU-1007":"1007",
  "PEU-106":"106",
  "PEU-107":"107",
  "PEU-108":"108",
  "PEU-2008":"2008",
  "PEU-206":"206",
  "PEU-206 +":"206+",
  "PEU-206 cc":"206C",
  "PEU-206 sw":"206S",
  "PEU-207":"207",
  "PEU-207 +":"207+",
  "PEU-207 cc":"207C",
  "PEU-207 sw":"207S",
  "PEU-208":"208",
  "PEU-3008":"3008",
  "PEU-301":"301",
  "PEU-306":"306",
  "PEU-307":"307",
  "PEU-307 cc":"307C",
  "PEU-307 sw":"307S",
  "PEU-308":"308",
  "PEU-308 cc":"308C",
  "PEU-308 sw":"308S",
  "PEU-4007":"4007",
  "PEU-4008":"4008",
  "PEU-406":"406",
  "PEU-407":"407",
  "PEU-5008":"5008",
  "PEU-508":"508",
  "PEU-508 sw":"508S",
  "PEU-607":"607",
  "PEU-807":"807",
  "PEU-bipper":"BIP",
  "PEU-boxer":"BOX",
  "PEU-expert":"EXP",
  "PEU-partner":"PAR",
  "PEU-rcz":"RCZ",
  "PEU-rifter":"RIF",
  "PEU-traveller":"TRA",
  "REN-captur":"CAP",
  "REN-clio 2":"CLI2",
  "REN-clio 3":"CLI3",
  "REN-clio 4":"CLI4",
  "REN-clio 5":"CLI5",
  "REN-clio campus":"CLICA",
  "REN-espace 4":"ESP4",
  "REN-espace 5":"ESP5",
  "REN-fluence":"FLU",
  "REN-grand scenic 2":"GSCE2",
  "REN-grand scenic 3":"GSCE3",
  "REN-grand scenic 4":"GSCE4",
  "REN-kadjar":"KAD",
  "REN-kangoo":"KAN",
  "REN-koleos":"KOL",
  "REN-laguna 2":"LAG2",
  "REN-laguna 3":"LAG3",
  "REN-master":"MAS",
  "REN-megane 1":"MEG1",
  "REN-megane 2":"MEG2",
  "REN-megane 3":"MEG3",
  "REN-megane 3 cc":"MEG3CC",
  "REN-megane 4":"MEG4",
  "REN-modus":"MOD",
  "REN-scenic 1":"SCE1",
  "REN-scenic 2":"SCE2",
  "REN-scenic 3":"SCE3",
  "REN-scenic 4":"SCE4",
  "REN-symbol":"SYMB",
  "REN-talisman":"TAL",
  "REN-trafic":"TRA",
  "REN-twingo":"TWI",
  "REN-twingo 2":"TWI2",
  "REN-twingo 3":"TWI3",
  "REN-vel satis":"VEL",
  "REN-zoe":"ZOE",
  "SEA-alhambra":"ALH",
  "SEA-altea":"ALT",
  "SEA-arona":"ARON",
  "SEA-arosa":"AROS",
  "SEA-ateca":"ATE",
  "SEA-cordoba":"COR",
  "SEA-ibiza":"IBI",
  "SEA-leon":"LEO",
  "SEA-toledo":"TOL",
  "SKO-citigo":"CIT",
  "SKO-fabia":"FAB",
  "SKO-kamiq":"KAM",
  "SKO-karoq":"KAR",
  "SKO-kodiaq":"KOD",
  "SKO-octavia":"OCT",
  "SKO-rapid":"RAP",
  "SKO-roomster":"ROO",
  "SKO-scala":"SCA",
  "SKO-superb":"SUP",
  "SKO-yeti":"YET",
  "SMA-city":"CITY",
  "SMA-forfour":"FORF",
  "SMA-fortwo":"FORT",
  "SMA-passion":"PASS",
  "SMA-pulse":"PULS",
  "SMA-roadster":"ROAD",
  "SUZ-alto":"ALT",
  "SUZ-grand vitara":"GVI",
  "SUZ-ignis 1":"IGN1",
  "SUZ-ignis 2":"IGN2",
  "SUZ-ignis 3":"IGN3",
  "SUZ-pixo":"PIX",
  "SUZ-splash":"SPL",
  "SUZ-swift":"SWI",
  "SUZ-sx4":"SX4",
  "SUZ-wagon r":"WAGR",
  "TOY-auris":"AUR",
  "TOY-avensis":"AVE",
  "TOY-aygo":"AYG",
  "TOY-celica":"CEL",
  "TOY-corolla":"COR",
  "TOY-corolla verso":"CORV",
  "TOY-hiace":"HIA",
  "TOY-hilux":"HIL",
  "TOY-iq":"IQ",
  "TOY-land cruiser":"LCR",
  "TOY-previa":"PRE",
  "TOY-prius":"PRI",
  "TOY-pro ace":"PROA",
  "TOY-rav4":"RAV4",
  "TOY-urban cruiser":"URBC",
  "TOY-verso":"VERS",
  "TOY-yaris":"YAR",
  "VLK-amarok":"AMA",
  "VLK-arteon":"ART",
  "VLK-beetle":"BEE",
  "VLK-beetle cabriolet":"BEEC",
  "VLK-bora":"BOR",
  "VLK-caddy":"CAD",
  "VLK-crafter":"CRA",
  "VLK-eos":"EOS",
  "VLK-golf":"GOL",
  "VLK-golf cabriolet":"GOLC",
  "VLK-golf estate":"GOLE",
  "VLK-golf mk4":"GOLMK4",
  "VLK-golf mk6":"GOLMK6",
  "VLK-jetta":"JET",
  "VLK-passat":"PAS",
  "VLK-passat cc":"PASCC",
  "VLK-phaeton":"PHAE",
  "VLK-polo":"POL",
  "VLK-scirocco":"SCI",
  "VLK-sharan":"SHA",
  "VLK-t-cross":"TCR",
  "VLK-t-roc":"TRO",
  "VLK-tiguan":"TIG",
  "VLK-touareg":"TOUA",
  "VLK-touran":"TOUR",
  "VLK-transporter":"TRA",
  "VLK-transporter t6":"TRAT6",
  "VLK-up":"UP",
  "VOL-s60":"S60",
  "VOL-s80":"S80",
  "VOL-s80l":"S80L",
  "VOL-v40":"V40",
  "VOL-v60":"V60",
  "VOL-v70":"V70",
  "VOL-xc60":"XC60",
  "VOL-xc70":"XC70",
};
