/***
 *
 * List of Special Make or Model Values (When it's not just Capitalizing the first letter of each word)
 *
 * Left argument = Value used as a reference to the make or model  (defined in Make.ts and Model.ts)
 * Right argument = Value used in the "make" and "model" columns in the csv, the meta description, the base product name and variant product name
 *
 ***/
export const SpecialMakeModelNames : {[key: string]: string}  =
{
  "gt":"GT",
  "rs3":"RS3",
  "rs6":"RS6",
  "tt":"TT",
  "300c":"300C",
  "pt cruiser":"PT Cruiser",
  "c-crosser":"C-Crosser",
  "c-elysée":"C-Elysée",
  "ds3":"DS3",
  "ds4":"DS4",
  "ds5":"DS5",
  "ds7 crossback":"DS7 Crossback",
  "ds9":"DS9",
  "500l":"500L",
  "500X":"500X",
  "b-max":"B-Max",
  "c-max":"C-Max",
  "grand c-max":"Grand C-Max",
  "s-max":"S-Max",
  "cr-v":"CR-V",
  "cr-z":"CR-Z",
  "fr-v":"FR-V",
  "hr-v":"HR-V",
  "ix35":"IX35",
  "e-pace":"E-PACE",
  "f-pace":"F-PACE",
  "i-pace":"I-PACE",
  "xf":"XF",
  "xk":"XK",
  "clk":"CLK",
  "cls":"CLS",
  "slc":"SLC",
  "slk":"SLK",
  "megane 3 cc":"Megane 3 CC",
  "asx":"ASX",
  "350z":"350Z",
  "e-nv200":"e-NV200",
  "np300":"NP300",
  "nv200":"NV200",
  "nv300":"NV300",
  "nv400":"NV400",
  "x-trail":"X-Trail",
  "x-trail t30":"X-Trail T30",
  "206 cc":"206 CC",
  "206 sw":"206 SW",
  "207 cc":"207 CC",
  "207 sw":"207 SW",
  "307 cc":"307 CC",
  "307 sw":"307 SW",
  "308 cc":"308 CC",
  "308 sw":"308 SW",
  "508 sw":"508 SW",
  "rcz":"RCZ",
  "sx4":"SX4",
  "iq":"iQ",
  "rav4":"RAV4",
  "eos":"EOS",
  "passat cc":"Passat CC",
  "t-cross":"T-Cross",
  "t-roc":"T-Roc",
  "xc60":"XC60",
  "xc70":"XC70",
  "bmw":"BMW", //Moto aussi
  "ds automobiles":"DS Automobiles",
  "classe cl":"Classe CL",
  "classe gl":"Classe GL",
  "classe sl":"Classe SL",
  "pro-ceed":"Pro-Ceed",
  "golf mk6":"Golf MK6",
  "golf mk4":"Golf MK4",

  //Moto
  "ktm":"KTM",
}
